name: local
variables:
  - name: basePath
    value: https://apps-local.steubing.com
  - name: brokerSideOrdersPath
    value: /broker-side/orders
  - name: brokerSideTradesPath
    value: /broker-side/trades
  - name: clientSideOrdersPath
    value: /client-side/orders
  - name: clientSideTradesPath
    value: /client-side/trades
  - name: allocationBatchesPath
    value: /allocation/batches
  - name: allocationLinesPath
    value: /allocation/lines
  - name: masterDataVenuesPath
    value: /master-data/venues
  - name: masterDataClientsPath
    value: /master-data/clients
  - name: masterDataBrokersPath
    value: /master-data/brokers
  - name: masterDataInstrumentsPath
    value: /master-data/instruments
